# Generated by Django 4.2 on 2025-05-05 01:47

import consignment.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_address', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_email', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(default=consignment.models.generate_tracking_code, max_length=32, unique=True)),
                ('package_id', models.CharField(default=consignment.models.generate_package_id, max_length=20, unique=True)),
                ('package_name', models.CharField(max_length=100)),
                ('sending_location', models.CharField(blank=True, max_length=100, null=True)),
                ('receiving_location', models.CharField(blank=True, max_length=100, null=True)),
                ('current_location', models.CharField(blank=True, help_text='name for map iframe', max_length=300, null=True)),
                ('package_description', models.TextField(blank=True, null=True)),
                ('mode_of_transit', models.CharField(choices=[('Air', 'Air'), ('Sea', 'Sea'), ('Road', 'Road')], max_length=10)),
                ('package_status', models.CharField(choices=[('Shipment Processed', 'Shipment Processed'), ('In Transit', 'In Transit'), ('Awaiting Customs Clearance', 'Awaiting Customs Clearance'), ('Customs Cleared', 'Customs Cleared'), ('At Destination Facility', 'At Destination Facility'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Returned', 'Returned'), ('Cancelled', 'Cancelled')], max_length=32)),
                ('delivery_update', models.TextField(blank=True, null=True)),
                ('package_image', models.ImageField(default='default_image.jpg', upload_to='package_images/')),
                ('package_weight', models.FloatField(blank=True, default=0.0, null=True)),
                ('shipping_cost', models.FloatField(blank=True, default=0.0, null=True)),
                ('package_quantity', models.IntegerField(default=1)),
                ('shipping_date', models.DateField(auto_now=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='consignment.customer')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='consignment.customer')),
            ],
            options={
                'verbose_name_plural': 'Packages',
            },
        ),
    ]
