# Generated by Django 4.2 on 2025-05-05 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='email',
            field=models.EmailField(blank=True, help_text='receiver email address', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='tel',
            field=models.CharField(blank=True, help_text='receiver phone number', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='receiver',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='receiving_location',
            field=models.CharField(blank=True, help_text='receiver address & city', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='sender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='sending_location',
            field=models.CharField(blank=True, help_text='sender address & city', max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
