# Generated by Django 4.2 on 2025-05-05 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0002_package_email_package_tel_alter_package_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='delivery_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
