# Generated by Django 4.2 on 2025-05-09 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0003_alter_package_delivery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='package_image',
        ),
    ]
