# Generated by Django 4.2 on 2025-05-31 16:30

import consignment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0004_remove_package_package_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='delivery_date',
            field=models.DateTimeField(blank=True, default=consignment.models.default_delivery_date, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='shipping_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
