# Generated by Django 4.2 on 2025-05-31 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0007_alter_package_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='shipping_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
