# Generated by Django 4.2 on 2025-05-31 16:45

import consignment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0008_alter_package_shipping_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='delivery_date',
            field=models.DateField(blank=True, default=consignment.models.default_delivery_date, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='shipping_date',
            field=models.DateField(blank=True, default=consignment.models.default_shipping_date, null=True),
        ),
    ]
