# Generated by Django 4.2 on 2025-10-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0009_alter_package_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='package_status',
            field=models.CharField(choices=[('Shipment Processed', 'Shipment Processed'), ('In Transit', 'In Transit'), ('Hold', 'Hold'), ('At Destination Facility', 'At Destination Facility'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Returned', 'Returned'), ('Cancelled', 'Cancelled')], max_length=32),
        ),
    ]
