# Generated by Django 4.2 on 2025-10-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0010_alter_package_package_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='package_status',
            field=models.CharField(choices=[('Shipment Processed', 'Shipment Processed'), ('In Transit', 'In Transit'), ('Hold', 'Hold'), ('Delivered', 'Delivered')], max_length=32),
        ),
    ]
