# Generated by Django 4.2 on 2025-10-07 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0011_alter_package_package_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='shipping_cost',
        ),
    ]
